name = "MultistateModelsTests"
uuid = "e3a6b8f0-3f9f-4b8d-9e4b-3f1a6c8db2d3"
version = "0.1.0"

[deps]
MultistateModels = "0f8f0c3e-0b3a-5b8a-9e9a-0a0a0a0a0a0a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
BSplineKit = "093aae92-e908-43d7-9660-e50ee39d5a0a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ParameterHandling = "2412ca09-6db7-441c-8e3a-88d5709968c5"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"