[compat]
Documenter = "1"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
MultistateModels = "0f8f0c3e-0b3a-5b8a-9e9a-0a0a0a0a0a0a"

[extras]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
